[package]
name = "helios-omicron-brand"
version = "0.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.47"
flate2 = "1.0.22"
getopts = "0.2.21"
libc = "0.2.108"
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
tar = "0.4.37"
tempfile = "3.2.0"
walkdir = "2.3.2"
