[package]
name = "helios-build-utils"
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = { workspace = true }
serde = { workspace = true }
tar = { workspace = true }
serde_json = { workspace = true }
walkdir = { workspace = true }
